### ISSUE TITLE
Adding Prettier Formatter

### ISSUE THREAD

**Issue by kauppfbi** [angular-schule/ngx-deploy-starter#10]
Hi, 

When I forked the project, adding Prettier was one of my first steps.
As it is very popular and provides standard formatting for every contribution, I suggest to use [Prettier](https://prettier.io/). 

If you like me to do so, I would prepare a PR with Prettier configured. I could also add pretty-quick and husky to enforce formatting in a pre-commit hook.

Let me know how you think about it :ear:

**Comment by JohannesHoppe** [comment]
If you not only add it, but also format everything: please do so! 😉

**Comment by dianjuar** [comment]
I also set prettier in [ngx-deploy-npm](npmjs.com/ngx-deploy-npm)

Is very useful and I love it

**Comment by JohannesHoppe** [comment]
@kauppfbi Thanks for the PR! This is my first time using prettier and I like it. 😄👍 

Since `ngx-deploy-starter` is an example project, we should make it as easy as possible for a  beginner.

1. We need some README in the docs with a short introduction.
    * an explanation of `--check` and `--write`
    * some words about pretty-quick and the husky pre-commit hook

2. I also think the pattern must be adjusted:

```
cd src
npx prettier -c ./*
```
will only look at files from the top level. But we also have the `deploy` and `engine` folder. 
When I run `npx prettier --write '**/*'` i get some nasty errors:

```
[error] No parser could be inferred for file: .DS_Store
[error] No parser could be inferred for file: dist/deploy/actions.js.map
```
So my silly `.DS_Store` and the `dist` folder should be ignored.

Can you help me out?  😇

**Comment by fmalcher** [comment]
Related side note: We should also enable "formatOnSave" for VSCode so that prettier runs whenever you hit save in the editor. Super useful in the workflow because you never need to think about how to format code again.

**Comment by kauppfbi** [comment]
Hi @JohannesHoppe, 

sure, I can help you with that. 

Then I will prepare a PR with
1. Some Docs about the setup and tooling
2. Adjustments of the pattern 
3. VSCode settings for formatOnSave + prettier as recommend plugin 

fine for you?

**Comment by JohannesHoppe** [comment]
Sounds awesome! 👍
