### ISSUE TITLE
Mark repository as template

### ISSUE THREAD

**Issue by EdricChan03** [angular-schule/ngx-deploy-starter#16]
This allows other users to easily create a deploy tool from the existing code. See this [help article](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository) for more info on template repositories.

Once the repository is marked as a template, a "Use this template" button will be shown above the file list. See this [help article](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template) for more info.

**Comment by JohannesHoppe** [comment]
That sounds very reasonable. I'm gonna try this. Hopefully new repos will still be visible as forks?!

**Comment by JohannesHoppe** [comment]
I think I do not think this feature is very much useful. When I "use this template" (instead of a fork), the new repo is not shown in the list of forks. Currently I use the list of forks to discover new repos and keep track of them... :-/
<img width="327" alt="Screen Shot 2020-01-03 at 01 37 55" src="https://user-images.githubusercontent.com/640639/71701565-89fe2780-2dca-11ea-8528-3128e4602865.png">
In this example, https://github.com/johanneshoppe/test is not shown here.
